socialPage/urls.py
from django.urls import path 
from .views import PostListView, PostCreateView, PostDetailView, PostEditView, PostDeleteView, CommentDeleteView
from .views import ProfileView, ProfileEditView, AddFollower, RemoveFollower, AddLike, AddDislike, FollowerList
from .views import UserSearch, SingleItemView, GroceryListView

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/like', AddLike.as_view(), name='like'),
    path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/', FollowerList.as_view(), name='follower-list'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('grocery_list/', GroceryListView.as_view(), name='grocery-list'),
    path('add_item/', SingleItemView.as_view(), name='add-item'),
   
]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('landingPage.urls')),
    path('socialPage/', include('socialPage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

socialPage/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

#Post
class Post(models.Model):
    body = models.TextField()
    image = models.ImageField(upload_to='uploads/post_photos', blank=True, null=True, max_length=1000)
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(User, blank=True, related_name='dislikes')

#Comment
class Comment(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

#Profile
class UserProfile(models.Model):
    ROLE_CHOICES = (
        ('Restaurateur', 'restaurateur'),
        ('Amateur chef', 'amateur chef'),
    )

    user = models.OneToOneField(User, primary_key=True, verbose_name='user', related_name='profile', on_delete=models.CASCADE)
    name = models.CharField(max_length=30, blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, blank=True, null=True)
    picture = models.ImageField(upload_to='uploads/profile_pictures', default='uploads/profile_pictures/defaultProfile.jpg', blank=True, max_length=1000)
    followers = models.ManyToManyField(User, blank=True, related_name='followers')
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


#Single item  
class SingleItem(models.Model):
    NAME_CHOICES = (
        ('Meat or Fish','meat or fish'),
        ('Frozen goods','frozen goods'),
        ('Canned food','canned food'),
        ('Fruits','fruits'),
        ('Vegetables','vegetables'),
        ('Dairy', 'dairy'),
        ('Nuts','nuts'),
        ('Eggs','eggs'),
        ('Pasta','pasta'),
        ('Bread','bread'),
        ('Salty snacks','salty snacks'),
        ('Sweet snacks','sweet snacks'),
        ('Pastry','pastry'),
        ('Water or Soft drinks','water or soft drinks'),
        ('Energy drinks','energy drinks'),
        ('Alcoholic drinks','alcoholic drinks'),
        ('Coffee or Tea','coffee or tea'),
        ('Spices','spices'),
        ('Seasoning','seasoning'),
    )
    STORAGE_CHOICES = (
            ('Pantry', 'pantry'),
            ('Fridge', 'fridge'),
            ('Freezer', 'freezer'),
            ('Other', 'other'),
        )

    item_name = models.CharField(max_length=50, blank=True)
    food_category = models.CharField(max_length=50, choices=NAME_CHOICES, blank=True, null=True)
    storage_method = models.CharField(max_length=30, choices=STORAGE_CHOICES, blank=True, null=True)
    expiration_date = models.DateField(blank=True, null=True)


#Grocery list
class GroceryList(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True, default='grocery list')
    list_owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, to_field='username')
    grocery_items = models.ManyToManyField(SingleItem, blank=True, related_name='grocery_items')

    def save(self, *args, **kwargs):
        if not self.list_owner:
            self.list_owner = User.objects.get(username='default')
        super().save(*args, **kwargs)

socialPage/forms.py
from django import forms
from .models import Post, Comment, SingleItem, GroceryList

# Post form
class PostForm(forms.ModelForm):
    body = forms.CharField(
        label = '',
        widget = forms.Textarea(attrs = {
            'rows' : '3',
            'placeholder' : 'Write something ...'
        })
    ) 

    images = forms.ImageField(required=False)

    class Meta:
        model = Post
        fields = ['body', 'image']


#Comment form 
class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label = '',
        widget = forms.Textarea(attrs = {
            'rows' : '3',
            'placeholder' : 'Write something ...'
        })
    ) 

    class Meta:
        model = Comment
        fields = ['comment']


#Single possible grocery list item form 
class SingleItemForm(forms.ModelForm):
    class Meta:
        model = SingleItem
        fields = ['item_name', 'food_category', 'storage_method', 'expiration_date']


#Grocery list form 
class GroceryListForm(forms.ModelForm):
    grocery_items = forms.ModelMultipleChoiceField(queryset=SingleItem.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = GroceryList
        fields = ['name', 'list_owner', 'grocery_items']

socialPage/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views import View
from .models import Post, Comment, UserProfile, SingleItem, GroceryList
from .forms import PostForm, CommentForm, SingleItemForm, GroceryListForm
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView, DeleteView

#Create a post 
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'socialPage/post_create.html'
    success_url = reverse_lazy('post-list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


#Feed 
class PostListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs): 
        logged_in_user = request.user 
        post = Post.objects.filter(
            author__profile__followers__in = [logged_in_user.id]
        ).order_by('-created_on')
        form = PostForm()

        context = {
            'post_list' : post,
            'form' : form,
        }

        return render(request, 'socialPage/post_list.html', context)

    def post(self, request, *args, **kwargs): 
        logged_in_user = request.user 
        post = Post.objects.filter(
            author__profile__followers__in = [logged_in_user.id]
        ).order_by('-created_on')
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()

        context = {
            'post_list' : post,
            'form' : form,
        }
        return render(request, 'socialPage/post_list.html', context)


#Detailed post with related comments 
class PostDetailView(LoginRequiredMixin, View):
     def get(self, request, pk, *args, **kwargs):  
        post = Post.objects.get(pk=pk)
        form = CommentForm()

        comments = Comment.objects.filter(post=post).order_by('-created_on')

        context = {
            'post' : post,
            'form' : form,
            'comments' : comments,
        }

        return render(request, 'socialPage/post_detail.html', context)

    # For adding a comment 
     def post(self, request, pk, *args, **kwargs): 
        post = Post.objects.get(pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

        comments = Comment.objects.filter(post=post).order_by('-created_on')

        context = {
            'post' : post,
            'form' : form,
            'comments' : comments 
        }

        return render(request, 'socialPage/post_detail.html', context)


#Post edit and delete 
class PostEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['body']
    template_name = 'socialPage/post_edit.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('post-detail', kwargs={'pk' : pk})

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'socialPage/post_delete.html'
    success_url = reverse_lazy('post-list')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


#Delete a comment
class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'socialPage/comment_delete.html'

    def get_success_url(self):
        pk = self.kwargs['post_pk']
        return reverse_lazy('post-detail', kwargs={'pk' : pk})

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


#Profile 
class ProfileView(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        user = profile.user
        posts = Post.objects.filter(author=user).order_by('-created_on')

        followers = profile.followers.all()

        if len(followers) == 0:
            is_following = False

        for follower in followers:
            if follower == request.user:
                is_following = True
                break
            else:
                is_following = False

        number_of_followers = len(followers)

        context = {
            'user' : user,
            'profile' : profile,
            'posts' : posts,  
            'number_of_followers' : number_of_followers,
            'is_following' : is_following,
        }

        return render(request, 'socialPage/profile.html', context)


#Profile edit
class ProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = UserProfile
    fields = ['name','bio','role','birth_date','location','picture']
    template_name = 'socialPage/profile_edit.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('profile', kwargs={'pk': pk})

    def test_func(self):
        profile = self.get_object()
        return self.request.user == profile.user


#Adding and removing a follower 
class AddFollower(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        profile.followers.add(request.user)

        return redirect('profile', pk=profile.pk)

class RemoveFollower(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        profile.followers.remove(request.user)

        return redirect('profile', pk=profile.pk)


#Like and dislike 
class AddLike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_dislike = False 

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break
        
        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False 

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)
        
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

class AddDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_like = False 

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False 

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add (request.user)

        if is_dislike:
            post.dislikes.remove(request.user)
        
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


#Searching user 
class UserSearch(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('query')
        profile_list = UserProfile.objects.filter(
            Q(user__username__icontains = query )
        )

        context = {
            'profile_list': profile_list,
        }

        return render(request, 'socialPage/search.html', context)


#Followers list on a profile
class FollowerList(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        followers = profile.followers.all()

        context = {
            'profile' : profile,
            'followers' : followers, 
        }

        return render(request, 'socialPage/follower_list.html', context)


#Single items view
class SingleItemView(View):
    def get(self, request, *args, **kwargs):
        name = SingleItem.item_name
        category = SingleItem.food_category
        default_storage = SingleItem.storage_method
        default_expiration = SingleItem.expiration_date
        items = SingleItem.objects.all().order_by('item_name')

        context = {
            'name' : name,
            'category' : category,
            'default storage' : default_storage,
            'default expiration' : default_expiration,
            'items' : items,
        }

        return render(request, 'socialPage/add_item.html', context)


#Grocery list view
class GroceryListView(View):
    def get(self, request, *args, **kwargs):
        grocery_list = GroceryList.objects.get(list_owner=request.user)
        grocery_items = grocery_list.grocery_items.all()

        context = {
            'grocery_list': grocery_list,
            'grocery_items': grocery_items,
        }

        return render(request, 'socialPage/grocery_list.html', context)



socialPage/templates/socialPage/add_item.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="container">
    <!-- back to feed button -->
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'grocery-list' %}" class="btn btn-light"> Back to grocery list </a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-6 col-sm-12">  
            <h6>If the item you're searching for isn't already in our database : </h6>
            <!-- create a new item -->
            <div class="d-grid gap-2" style="padding-bottom: 20px;">
                <button class="btn" style="background-color: #fda742;"> 
                    <a href="#"  style="color: #fcfcfc"> Create a new item to add </a>
                </button>
            </div>
            <!-- divider -->
            <div class="row">
                <hr style="1px rounded #333; width: 100%">
            </div>

            <!-- add an existing item -->
            <h4>Already existing items inside the database</h4>
            <!-- divider -->
            <div class="row">
                <hr style="1px rounded #333; width: 100%">
            </div>
            <!-- items list -->
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                      <tr>
                        <th scope="col">Item name</th>
                        <th scope="col">Category</th>
                        <th scope="col"> </th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}
                        <tr>
                            <td>{{ item.item_name }}</td>
                            <td>{{ item.food_category }}</td>
                            <td>
                                <button type="button" class="btn btn-outline-success">
                                    <i class="fa-regular fa-plus"></i>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>  

</div>

{% endblock content %}

socialPage/templates/socialPage/comment_delete.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="container">
    <!-- back to post button -->
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'post-detail' object.post.pk %}" class="btn btn-light">Back to post</a>
        </div>
    </div>


    <div class="row justify-content-center mt-3 mb-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST">
                {% csrf_token %}
                <h5> Are you sure? </h5>
                <p> You are about to delete this comment, this cannot be undone. </p>
                <div class="d-grid gap-2">
                    <button class="btn btn-dark mt-3"> Delete </button>
                </div>
            </form>
        </div>
    </div>

    
</div>

{% endblock content %}

socialPage/templates/socialPage/follower_list.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="container">
    <!-- back to profile button -->
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'profile' profile.pk %}" class="btn btn-light">Back to profile</a>
        </div>
    </div>

    <!-- head -->
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 border-bottom">
            {% if profile.name %}
            <h4> <i>{{ profile.name }}</i> followers </h4>
            {% else %}
            <h4> <i>@{{ profile.user.username }}</i> followers </h4>
            {% endif %}
        </div>
    </div>

    <!-- divider -->
    <div class="row justify-content-center">
        <hr style="1px rounded #333; width: 80%">
    </div>

    <!-- followers list -->
    {% for follower in followers %}
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom position-relative">
            <!-- profile icon -->
            <a href="{% url 'profile' follower.profile.pk %}">
                <img class="rounded-circle" style="float: left; margin-right: 1rem" height="30" width="30" src="{{ follower.profile.picture.url }}"/>
            </a>
            <!-- profile username  --> 
            <p><a srtyle="text-decoration: none" class="text-primary" href="{% url 'profile' follower.profile.pk %}"> 
                @ {{ follower.profile.user }} </a> </p>
            <!-- profile location -->
            {% if follower.profile.location %}
            <p> {{ follower.profile.location }} </p>
            {% endif %}
            <!-- profile followers -->
            <p> {{ follower.profile.followers.all.count }} followers </p>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock content %}

socialPage/templates/socialPage/post_create.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <!-- back to feed button -->
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'post-list' %}" class="btn btn-light">Back to feed</a>
        </div>
    </div>

    
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- body -->
                <div class="form-group">
                    <label for="id_body">Write something </label>
                    <input type="text" class="form-control" id="id_body" name="body" value="{{ form.body.value }}">
                    {% if form.body.errors %}
                    {% for error in form.body.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- image -->
                <div class="form-group mb-3">
                    <label for="post_image" class="form-label">Upload image :</label>
                    <input type="file" class="form-control" id="id_image" name="image">
                    {% if form.image.errors %}
                    {% for error in form.image.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- submit button -->
                <div class="d-grid gap-2">
                    <button class="btn mt-3" style="background-color: #fda742; color: #fcfcfc"> Submit </button>
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock content %}

socialPage/templates/socialPage/post_delete.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="container">
    <!-- back to post button -->
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'post-detail' object.pk %}" class="btn btn-light">Back to post</a>
        </div>
    </div>


    <div class="row justify-content-center mt-3 mb-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST">
                {% csrf_token %}
                <h5> Are you sure? </h5>
                <p> You are about to delete this post, this cannot be undone. </p>
                <div class="d-grid gap-2">
                    <button class="btn btn-dark mt-3"> Delete </button>
                </div>
            </form>
        </div>
    </div>

    
</div>

{% endblock content %}

socialPage/templates/socialPage/post_edit.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <!-- back to post button -->
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'post-detail' object.pk %}" class="btn btn-light">Back to post</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h5> Update your post! </h5>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- body -->
            <div class="form-group {% if form.body.errors %} has-error {% endif %}">
                <label for="id_body">Body</label>
                <textarea class="form-control" id="id_body" name="body" rows="3">{{ form.body.value }}</textarea>
                {% for error in form.body.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div> 
            <!-- image -->
            <div class="form-group" {% if form.image.errors %} has-error {% endif %}>
                <label for="id_image">Image</label>
                <img type="file" class="form-control-file" id="id_image" name="image" multiple>{{ form.image.value }}</img>
                {% for error in form.image.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            
            <div class="d-grid gap-2">
                <button class="btn mt-3" style="background-color: #fda742; color: #fcfcfc"> Submit </button>
            </div>
            </form>  
        </div>
    </div>

    


    
</div>

{% endblock content %}

socialPage/templates/socialPage/profile_edit.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <!-- back to user profile button -->
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'profile' object.pk %}" class="btn btn-light">Back to profile</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h5>Update your profile</h5>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">

            <!-- form fields -->
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- name -->
                <div class="form-group">
                    <label for="id_name">Name : </label>
                    <input type="text" class="form-control" id="id_name" name="name" value="{{ form.name.value }}">
                    {% if form.name.errors%}
                    {% for error in form.name.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- user icon -->
                <div class="form-group mb-3">
                    <label for="id_picture" class="form-label">Profile picture :</label>
                    <input type="file" class="form-control" id="id_picture" name="image" value="{{ form.image.value }}">
                    {% if form.image.errors %}
                        {% for error in form.image.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
                <!-- bio -->
                <div class="form-group">
                    <label for="id_bio">Bio : </label>
                    <input type="text" class="form-control" id="id_bio" name="bio" value="{{ form.bio.value }}">
                    {% if form.bio.errors %}
                    {% for error in form.bio.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- birthday -->
                <div class="form-group">
                    <label for="id_birth_date">Birth Date : </label>
                    <input type="date" class="form-control" id="id_birth_date" name="birth_date" value="{{ form.birth_date.value }}">
                    {% if form.birth_date.errors %}
                    {% for error in form.birth_date.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- location -->
                <div class="form-group">
                    <label for="id_location">Location : </label>
                    <input type="text" class="form-control" id="id_location" name="location" value="{{ form.location.value }}">
                    {%if form.location.errors.errors %}
                    {% for error in form.location.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- role -->
                <div class="form-group">
                    <label for="id_role">Role : </label>
                    <select class="form-select" id="id_role" name="role">
                    {% for key, value in form.role.field.choices %}
                        <option value="{{ key }}" {% if key == form.role.value %} selected {% endif %}> {{ value }} </option>
                    {% endfor %}
                    </select>
                    {% if form.role.errors %}
                    {% for error in form.role.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <!-- submit button -->
                <div class="form-group d-grid gap-2">
                    <button class="btn mt-3" style="background-color: #fda742; color: #fcfcfc"> Save changes </button>
                </div>
            </form>

        </div>
    </div>
     

</div>
{% endblock content %}